# Generated by Django 2.1.5 on 2019-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='points_redeemed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
