# Generated by Django 2.1.5 on 2019-02-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_reward_points_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='service_used',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
