# Generated by Django 2.1.5 on 2019-03-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_reward_service_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='redeem_status',
            field=models.IntegerField(choices=[(True, 'yes'), (False, 'no')], default=False, null=True),
        ),
    ]
