# Generated by Django 2.1.5 on 2019-03-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_reward_redeem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='redeem_status',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')], default=2, null=True),
        ),
    ]
