# Generated by Django 2.1.5 on 2019-03-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190301_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='redeem_status',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default=2, max_length=10, null=True),
        ),
    ]
