# Generated by Django 2.1.5 on 2019-03-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190301_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='redeem_status',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=10, null=True),
        ),
    ]
