# Generated by Django 2.1.5 on 2019-03-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('week', '0003_serviceformfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceformfield',
            name='page',
        ),
        migrations.DeleteModel(
            name='ServiceFormField',
        ),
    ]
